INSERT IGNORE INTO stocks
(stock_id, stock_name, ticker, stock_market)
VALUES
(1, 'Apple Inc.', 'AAPL', 'NASDAQ'),
(2, 'Microsoft Corporation', 'MSFT', 'NASDAQ'),
(3, 'NVIDIA Corporation', 'NVDA', 'NASDAQ'),
(4, 'Alphabet Inc.', 'GOOG', 'NASDAQ'),
(5, 'Broadcom Inc.', 'AVGO', 'NASDAQ'),
(6, 'Costco Wholesale Corporation', 'COST', 'NASDAQ'),
(7, 'Adobe Inc.', 'ADBE', 'NASDAQ'),
(8, 'JPMorgan Chase & Co.', 'JPM', 'NYSE'),
(9, 'Bank of America Corporation', 'BAC', 'NYSE'),
(10, 'Morgan Stanley', 'MS', 'NYSE'),
(11, 'Berkshire Hathaway Inc.', 'BRK-B', 'NYSE'),
(12, 'Johnson & Johnson', 'JNJ', 'NYSE'),
(13, 'Procter & Gamble Company', 'PG', 'NYSE'),
(14, 'Coca-Cola Company', 'KO', 'NYSE'),
(15, 'ICICI Bank Limited', 'ICICIBANK.NS', 'NSE'),
(16, 'HDFC Bank Limited', 'HDFCBANK.NS', 'NSE'),
(17, 'Infosys Limited', 'INFY.NS', 'NSE'),
(18, 'Tata Consultancy Services Limited', 'TCS.NS', 'NSE'),
(19, 'Reliance Industries Limited', 'RELIANCE.NS', 'NSE'),
(20, 'Axis Bank Limited', 'AXISBANK.NS', 'NSE'),
(21, 'Wipro Limited', 'WIPRO.NS', 'NSE'),
(22, 'Kotak Mahindra Bank Limited', 'KOTAKBANK.NS', 'NSE'),
(23, 'Larsen & Toubro Limited', 'LT.NS', 'NSE'),
(24, 'Bajaj Auto Limited', 'BAJAJ-AUTO.NS', 'NSE'),
(25, 'Maruti Suzuki India Limited', 'MARUTI.NS', 'NSE'),
(26, 'HCL Technologies Limited', 'HCLTECH.NS', 'NSE'),
(27, 'Tech Mahindra Limited', 'TECHM.NS', 'NSE'),
(28, 'ITC Limited', 'ITC.NS', 'NSE'),
(29, 'Bharti Airtel Limited', 'BHARTIARTL.NS', 'NSE'),
(30, 'Nestle India Limited', 'NESTLEIND.NS', 'NSE'),
(31, 'NTPC Limited', 'NTPC.NS', 'NSE'),
(32, 'Reliance Industries Limited', 'RELIANCE.BO', 'BSE'),
(33, 'ICICI Bank Limited', 'ICICIBANK.BO', 'BSE'),
(34, 'Tata Consultancy Services Limited', 'TCS.BO', 'BSE'),
(35, 'Bajaj Auto Limited', 'BAJAJ-AUTO.BO', 'BSE'),
(36, 'Maruti Suzuki India Limited', 'MARUTI.BO', 'BSE'),
(37, 'ITC Limited', 'ITC.BO', 'BSE'),
(38, 'Bharti Airtel Limited', 'BHARTIARTL.BO', 'BSE'),
(39, 'Titan Company Limited', 'TITAN.BO', 'BSE'),
(40, 'UltraTech Cement Limited', 'ULTRACEMCO.BO', 'BSE'),
(41, 'Bajaj Finance Limited', 'BAJFINANCE.BO', 'BSE'),
(42, 'Sun Pharmaceutical Industries Limited', 'SUNPHARMA.BO', 'BSE'),
(43, 'Power Grid Corporation of India Limited', 'POWERGRID.BO', 'BSE'),
(44, 'State Bank of India', 'SBIN.BO', 'BSE'),
(45, 'ASML Holding N.V.', 'ASML.AS', 'EURONEXT'),
(46, 'Unilever PLC', 'UNA.AS', 'EURONEXT'),
(47, 'TotalEnergies SE', 'TTE.PA', 'EURONEXT'),
(48, 'Schneider Electric SE', 'SU.PA', 'EURONEXT'),
(49, 'BNP Paribas SA', 'BNP.PA', 'EURONEXT'),
(50, 'Kering SA', 'KER.PA', 'EURONEXT'),
(51, 'AXA SA', 'CS.PA', 'EURONEXT');
