services:
  mysql:
    image: mysql:8.0
    container_name: beyond404-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "n3u3da!"
      MYSQL_DATABASE: beyond404
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pn3u3da!"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mysql_data: